apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-color
  labels:
    app: web-color
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-color
  template:
    metadata:
      labels:
        app: web-color
    spec:
      containers:
        - name: web-color
          image: fabricioveronez/web-color:blue
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-color
spec:
  selector:
    app: web-color
  type: NodePort
  ports:
    - name: http
      nodePort: 30950
      targetPort: 80
      port: 80
